#!/bin/bash

# run with -h for information
# http://www.timedicer.co.uk/programs/help/man2text.sh.php

VERSION="1.1 [10 May 2012]"
COLUMNS=$(stty size 2>/dev/null||echo 80); COLUMNS=${COLUMNS##* }
THIS=`basename $0`

while getopts ":hlw" optname; do
    case "$optname" in
		"h")	HELP=y;;
		"l")	CHANGELOG=y;;
		"w")	COLUMNS=30000;; #suppress line-breaking
		"?")	echo "Unknown option $OPTARG">&2; exit 99;;
		":")	echo "No argument value for option $OPTARG">&2; exit 99;;
		*)	# Should not occur
			echo "Unknown error while processing options">&2; exit 99;;
    esac
done

shift $(($OPTIND-1))

#echo -e "\n$THIS v$VERSION by Dominic (try -h for help)\n${THIS//?/=}\n"

if [ "$HELP" = "y" ]; then
	echo -e "A one-liner which converts a man page in GNU/Linux to \
straightforward text which can then be piped to a file or printer.

Usage       : man2text.sh command
Example     : ./man2text.sh ls
Options     : -h show help and exit
              -l show changelog and exit
Dependencies: GNU sed, man
License: Copyright 2014 Dominic Raferd. Licensed under the Apache License, \
Version 2.0 (the \"License\"); you may not use this file except in compliance \
with the License. You may obtain a copy of the License at \
http://www.apache.org/licenses/LICENSE-2.0. Unless required by applicable \
law or agreed to in writing, software distributed under the License is \
distributed on an \"AS IS\" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY \
KIND, either express or implied. See the License for the specific language \
governing permissions and limitations under the License.
"|fold -sw $COLUMNS
fi

if [ -n "$CHANGELOG" ]; then
	echo -e "1.1 [10 May 2012] - very minor changes to help/changelog
1.0 [25 Mar 2012] - original release
"
fi

[ -n "$CHANGELOG$EXIT" -o -z "$1" ] && exit

man $* | sed -r 's/\d027\[[0-9]+m//g'
