#! /usr/bin/env bash

# Copyright (c) 2014-2015 Abderraouf Adjal
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.


# for fxor (a tool to encrypt/decrypt a file using XOR operation to do one-time pad)

# Usage: opssl_rand IN_FILE_NAME OUT_FILE_NAME

# This script take IN_FILE_NAME size and run openssl command to make
# a random file (OUT_FILE_NAME), So OUT_FILE_NAME_SIZE = IN_FILE_NAME_SIZE


if ! [ "$#" -eq 2 ]; then
	printf 'Usage: %s IN_FILE_NAME OUT_FILE_NAME\n\n' "$0"
	printf 'This script take IN_FILE_NAME size and run openssl command to make\n'
	printf 'a random file (OUT_FILE_NAME), So OUT_FILE_NAME_SIZE = IN_FILE_NAME_SIZE\n'
	
	exit 64;
fi

openssl_rand_cmd=$(stat "$1" --format="openssl rand %s -out '$2'")

eval "$openssl_rand_cmd"
